import { useState } from "react";
import Post from "../components/Post";

const samplePosts = [
  {
    id: 1,
    title: "Introduction to React",
    author: "John Doe",
    content: "React is a JavaScript library for building user interfaces.",
    date: "2023-01-15",
    tags: ["React", "JavaScript", "Frontend"],
    likes: 120,
  },
  {
    id: 2,
    title: "Understanding State and Props",
    author: "Jane Smith",
    content: "State and props are essential concepts in React development.",
    date: "2023-02-10",
    tags: ["React", "State", "Props"],
    likes: 95,
  },
  {
    id: 3,
    title: "Building a Blog App with React",
    author: "Alice Johnson",
    content: "Learn how to build a simple blog application using React.",
    date: "2023-03-05",
    tags: ["React", "Blog", "Tutorial"],
    likes: 150,
  },
  {
    id: 4,
    title: "React Router Basics",
    author: "Chris Lee",
    content: "React Router helps in creating navigation for your app.",
    date: "2023-04-01",
    tags: ["React", "Router", "Navigation"],
    likes: 80,
  },
  {
    id: 5,
    title: "Using Context API",
    author: "Emma Brown",
    content: "Context API is a way to manage state globally in React.",
    date: "2023-04-15",
    tags: ["React", "Context API", "State Management"],
    likes: 110,
  },
  {
    id: 6,
    title: "React Performance Optimization",
    author: "Michael Green",
    content: "Learn how to optimize the performance of your React app.",
    date: "2023-05-10",
    tags: ["React", "Performance", "Optimization"],
    likes: 140,
  },
  {
    id: 7,
    title: "React Hooks Deep Dive",
    author: "Sophia White",
    content: "Understand React Hooks and how to use them effectively.",
    date: "2023-06-01",
    tags: ["React", "Hooks", "Advanced"],
    likes: 130,
  },
  {
    id: 8,
    title: "Styling in React",
    author: "Daniel Black",
    content: "Explore different ways to style your React components.",
    date: "2023-06-20",
    tags: ["React", "Styling", "CSS"],
    likes: 90,
  },
  {
    id: 9,
    title: "Testing React Applications",
    author: "Olivia Gray",
    content: "Learn how to test your React applications effectively.",
    date: "2023-07-05",
    tags: ["React", "Testing", "Jest"],
    likes: 100,
  },
  {
    id: 10,
    title: "React and TypeScript",
    author: "Liam Wilson",
    content: "Combine React with TypeScript for better type safety.",
    date: "2023-07-25",
    tags: ["React", "TypeScript", "Frontend"],
    likes: 125,
  },
  {
    id: 11,
    title: "React with Redux Toolkit",
    author: "Charlotte Davis",
    content: "Simplify state management with Redux Toolkit in React.",
    date: "2023-08-10",
    tags: ["React", "Redux", "State Management"],
    likes: 145,
  },
  {
    id: 12,
    title: "Deploying React Apps",
    author: "Ethan Martinez",
    content: "Learn how to deploy your React applications to production.",
    date: "2023-08-30",
    tags: ["React", "Deployment", "Production"],
    likes: 115,
  },
  {
    id: 1,
    title: "Introduction to React",
    author: "John Doe",
    content: "React is a JavaScript library for building user interfaces.",
    date: "2023-01-15",
    tags: ["React", "JavaScript", "Frontend"],
    likes: 120,
  },
  {
    id: 2,
    title: "Understanding State and Props",
    author: "Jane Smith",
    content: "State and props are essential concepts in React development.",
    date: "2023-02-10",
    tags: ["React", "State", "Props"],
    likes: 95,
  },
  {
    id: 3,
    title: "Building a Blog App with React",
    author: "Alice Johnson",
    content: "Learn how to build a simple blog application using React.",
    date: "2023-03-05",
    tags: ["React", "Blog", "Tutorial"],
    likes: 150,
  },
  {
    id: 4,
    title: "React Router Basics",
    author: "Chris Lee",
    content: "React Router helps in creating navigation for your app.",
    date: "2023-04-01",
    tags: ["React", "Router", "Navigation"],
    likes: 80,
  },
  {
    id: 5,
    title: "Using Context API",
    author: "Emma Brown",
    content: "Context API is a way to manage state globally in React.",
    date: "2023-04-15",
    tags: ["React", "Context API", "State Management"],
    likes: 110,
  },
  {
    id: 6,
    title: "React Performance Optimization",
    author: "Michael Green",
    content: "Learn how to optimize the performance of your React app.",
    date: "2023-05-10",
    tags: ["React", "Performance", "Optimization"],
    likes: 140,
  },
  {
    id: 7,
    title: "React Hooks Deep Dive",
    author: "Sophia White",
    content: "Understand React Hooks and how to use them effectively.",
    date: "2023-06-01",
    tags: ["React", "Hooks", "Advanced"],
    likes: 130,
  },
  {
    id: 8,
    title: "Styling in React",
    author: "Daniel Black",
    content: "Explore different ways to style your React components.",
    date: "2023-06-20",
    tags: ["React", "Styling", "CSS"],
    likes: 90,
  },
  {
    id: 9,
    title: "Testing React Applications",
    author: "Olivia Gray",
    content: "Learn how to test your React applications effectively.",
    date: "2023-07-05",
    tags: ["React", "Testing", "Jest"],
    likes: 100,
  },
  {
    id: 10,
    title: "React and TypeScript",
    author: "Liam Wilson",
    content: "Combine React with TypeScript for better type safety.",
    date: "2023-07-25",
    tags: ["React", "TypeScript", "Frontend"],
    likes: 125,
  },
  {
    id: 11,
    title: "React with Redux Toolkit",
    author: "Charlotte Davis",
    content: "Simplify state management with Redux Toolkit in React.",
    date: "2023-08-10",
    tags: ["React", "Redux", "State Management"],
    likes: 145,
  },
  {
    id: 12,
    title: "Deploying React Apps",
    author: "Ethan Martinez",
    content: "Learn how to deploy your React applications to production.",
    date: "2023-08-30",
    tags: ["React", "Deployment", "Production"],
    likes: 115,
  },
];

function PostPage() {
  const [posts, setPosts] = useState(samplePosts);
  console.log(posts);
  return (
    <div className="px-2 relative">
      <div className="mx-auto grid w-full max-w-7xl grid-cols-3 gap-4 py-4 md:grid-cols-4 lg:grid-cols-5 xl:grid-cols-6">
        {posts.map((p) => (
          <Post post={p} key={p.id} />
        ))}
      </div>
    </div>
  );
}

export default PostPage;
